/** Curated list of comforting / encouraging verse references. */
export const COMFORTING_VERSES: Array<{ book: string; chapter: number; verse: number }> = [
  { book: 'Psalms', chapter: 23, verse: 1 },
  { book: 'Psalms', chapter: 23, verse: 4 },
  { book: 'Psalms', chapter: 46, verse: 10 },
  { book: 'Psalms', chapter: 34, verse: 18 },
  { book: 'Psalms', chapter: 55, verse: 22 },
  { book: 'Psalms', chapter: 121, verse: 1 },
  { book: 'Psalms', chapter: 121, verse: 2 },
  { book: 'Psalms', chapter: 27, verse: 1 },
  { book: 'Psalms', chapter: 91, verse: 1 },
  { book: 'Psalms', chapter: 91, verse: 2 },
  { book: 'Psalms', chapter: 119, verse: 105 },
  { book: 'Psalms', chapter: 139, verse: 14 },
  { book: 'Proverbs', chapter: 3, verse: 5 },
  { book: 'Proverbs', chapter: 3, verse: 6 },
  { book: 'Isaiah', chapter: 41, verse: 10 },
  { book: 'Isaiah', chapter: 40, verse: 31 },
  { book: 'Isaiah', chapter: 26, verse: 3 },
  { book: 'Isaiah', chapter: 43, verse: 2 },
  { book: 'Jeremiah', chapter: 29, verse: 11 },
  { book: 'Lamentations', chapter: 3, verse: 22 },
  { book: 'Lamentations', chapter: 3, verse: 23 },
  { book: 'Matthew', chapter: 11, verse: 28 },
  { book: 'Matthew', chapter: 11, verse: 29 },
  { book: 'Matthew', chapter: 6, verse: 34 },
  { book: 'John', chapter: 14, verse: 27 },
  { book: 'John', chapter: 16, verse: 33 },
  { book: 'John', chapter: 3, verse: 16 },
  { book: 'Romans', chapter: 8, verse: 28 },
  { book: 'Romans', chapter: 8, verse: 38 },
  { book: 'Romans', chapter: 8, verse: 39 },
  { book: 'Romans', chapter: 15, verse: 13 },
  { book: '2 Corinthians', chapter: 4, verse: 16 },
  { book: '2 Corinthians', chapter: 4, verse: 17 },
  { book: '2 Corinthians', chapter: 12, verse: 9 },
  { book: 'Philippians', chapter: 4, verse: 6 },
  { book: 'Philippians', chapter: 4, verse: 7 },
  { book: 'Philippians', chapter: 4, verse: 13 },
  { book: '1 Peter', chapter: 5, verse: 7 },
  { book: 'Hebrews', chapter: 13, verse: 5 },
  { book: 'Revelation', chapter: 21, verse: 4 },
];
